apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-user
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  template:
    type: Opaque
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
  encryptedData:
    admin-user: AgCYdub9XpncyVQ3uxP4vGtW0gZiJ7uIY3Yhlnr07Vu4oh0xrBYqeYjYm6o7HFfhwdV0XjAhiYvLGqYqW950ERXGAOWvPcSwdNlFylyKLE78Inbho1FR8yK97FTvWP56aybREoWEF8lw+h83Ksv7qLhto+JWVw/yRDlr+cmPQw0wUJhP2zHylXGc7GOemA7SgpXcTq0OsroItc0alLC0Io7gtTuPk+WS7ewyGJ9+gKzNt5AQDOTe5U+aZE0yb+FaGcabolASp+iSImy2mMiYCQX6xqk+yUMHhM6K3Whbrn8aM/GCyPWUBPPcLemdXUnKfnp+wkEE3OZPNIfekvKge9ZOVGPzwGzQ16MhTga0Y8WvwTWmV3Jjtf8ZPknWT7miJC7JekNWfFlb7LNUN6OXTcXgzxzonk66RNV8Dz4wl1TgKZpibJp6d18EQtbtWIZaYysITIShmFSubHcFCJvWiPCMT/gT3XA5MEAEtVM9wWV+DU+QxoQK5FteEsl9QEHbctaFwZdfE/KYgA77pXrQWwFcNhs7cnvjyyjg5DdHjgKDXhvQtzzEPUqe+ZEKcL0tMVvAioBjtD1p3PwI+3V4SGr6tNEw6MQmrBcfSfdNGUyLgHpajf6zrYUzk0A0NxO3wP3cT48KYs+tzhMXxNHe5G65VisaCXrhLxZUkmtySsaLBgNj1fR+eVeizJ1zcKAVN2K7hHYdrlVecpgwWg==
    admin-password: AgCYdub9XpncyVQ3uxP4vGtW0gZiJ7uIY3Yhlnr07Vu4oh0xrBYqeYjYm6o7HFfhwdV0XjAhiYvLGqYqW950ERXGAOWvPcSwdNlFylyKLE78Inbho1FR8yK97FTvWP56aybREoWEF8lw+h83Ksv7qLhto+JWVw/yRDlr+cmPQw0wUJhP2zHylXGc7GOemA7SgpXcTq0OsroItc0alLC0Io7gtTuPk+WS7ewyGJ9+gKzNt5AQDOTe5U+aZE0yb+FaGcabolASp+iSImy2mMiYCQX6xqk+yUMHhM6K3Whbrn8aM/GCyPWUBPPcLemdXUnKfnp+wkEE3OZPNIfekvKge9ZOVGPzwGzQ16MhTga0Y8WvwTWmV3Jjtf8ZPknWT7miJC7JekNWfFlb7LNUN6OXTcXgzxzonk66RNV8Dz4wl1TgKZpibJp6d18EQtbtWIZaYysITIShmFSubHcFCJvWiPCMT/gT3XA5MEAEtVM9wWV+DU+QxoQK5FteEsl9QEHbctaFwZdfE/KYgA77pXrQWwFcNhs7cnvjyyjg5DdHjgKDXhvQtzzEPUqe+ZEKcL0tMVvAioBjtD1p3PwI+3V4SGr6tNEw6MQmrBcfSfdNGUyLgHpajf6zrYUzk0A0NxO3wP3cT48KYs+tzhMXxNHe5G65VisaCXrhLxZUkmtySsaLBgNj1fR+eVeizJ1zcKAVN2K7hHYdrlVecpgwWg==