apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-user
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  template:
    type: Opaque
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
  encryptedData:
    admin-user: AgAzB+I8GtEn3EhuYeOSVn76mGmC0i+18o522X2uO3p874ztCnGO+hYweAXHqVQ/Dteq5s+K0R90nrOpwPT1idk6wlTRgGlFHnpK+7iNuyUQRm1GfipoZOCvCYQ6OroLpD7b1YEKCBDZR1KSbddKpL3+D5FawAP0tE+Ifu4LtIHjq7asCeku5hyJfTQMy9N33GlJKrMs4CKGOaCCw+fYj0PnuazOknBp11j6xw17c6s+YbBnDbV6xhrp1VzyPpJqRtaNKHp/ru1TMWve58QEUMRzasbmZ5VQCVxyL83+Ba3RYSuIBxbNiJHZjy1STySblmePVvGsg8WIc8MfgJ51DdiJOHbeDc/gM3OUMEoMtqrvPlowvf1+MwL5E70L/vNiOWMCjOouXJVbz4Fxz7oW4cZKvAePf891S1SNlWSOIePVa3Z1f2JUllYINeNtQe+/2F037/6V71+8Cw8Iud5muax7SDGYMVn8R/pzmgaygna1CAyo2gaCAR/x4tYAW6E8mEeYnut9wJXOWRsoj/81C1hrmCocMyUb+C/d8FlBZOBblT/Hui1v69Q0OT8YiVArU0PWntJ9B2GqHiksQimpHG4HfMXD5L4WJ0hVkI/gQ0oylr+FsqBurAIXW3daRjEK7SZ2gCH1iQdYVjHtDLR7nLUiiPaUlHVAvHPs1cf4HwRiiuYupejVV/sAIOnQdKqeu1XjyJhNkpI+TvXK1A==
    admin-password: AgAzB+I8GtEn3EhuYeOSVn76mGmC0i+18o522X2uO3p874ztCnGO+hYweAXHqVQ/Dteq5s+K0R90nrOpwPT1idk6wlTRgGlFHnpK+7iNuyUQRm1GfipoZOCvCYQ6OroLpD7b1YEKCBDZR1KSbddKpL3+D5FawAP0tE+Ifu4LtIHjq7asCeku5hyJfTQMy9N33GlJKrMs4CKGOaCCw+fYj0PnuazOknBp11j6xw17c6s+YbBnDbV6xhrp1VzyPpJqRtaNKHp/ru1TMWve58QEUMRzasbmZ5VQCVxyL83+Ba3RYSuIBxbNiJHZjy1STySblmePVvGsg8WIc8MfgJ51DdiJOHbeDc/gM3OUMEoMtqrvPlowvf1+MwL5E70L/vNiOWMCjOouXJVbz4Fxz7oW4cZKvAePf891S1SNlWSOIePVa3Z1f2JUllYINeNtQe+/2F037/6V71+8Cw8Iud5muax7SDGYMVn8R/pzmgaygna1CAyo2gaCAR/x4tYAW6E8mEeYnut9wJXOWRsoj/81C1hrmCocMyUb+C/d8FlBZOBblT/Hui1v69Q0OT8YiVArU0PWntJ9B2GqHiksQimpHG4HfMXD5L4WJ0hVkI/gQ0oylr+FsqBurAIXW3daRjEK7SZ2gCH1iQdYVjHtDLR7nLUiiPaUlHVAvHPs1cf4HwRiiuYupejVV/sAIOnQdKqeu1XjyJhNkpI+TvXK1A==